language: node_js
node_js:
  - "11"

before_script:
  - npm run setup
  - npm run build

script:
  - npm run cover


after_script:
  "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

after_success:
  - npm run typedoc
  - npm pack


deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN

  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: lib.tgz
    skip_cleanup: true

  - provider: npm
    skip_cleanup: true
    email: ryderbrooks@gmail.com
    api_key: $NPM_TOKEN

